// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHfY9Ih_ZBvokT2VTcIcdQcWAa5v8g24M',
    appId: '1:285694691893:web:638402fa555a1f0791ff7c',
    messagingSenderId: '285694691893',
    projectId: 'aragaoconstrutora',
    authDomain: 'aragaoconstrutora.firebaseapp.com',
    storageBucket: 'aragaoconstrutora.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkvVUoZR9Gr0jMqyHXo89qndj9TEdtCdw',
    appId: '1:285694691893:android:8717b662acae9e4291ff7c',
    messagingSenderId: '285694691893',
    projectId: 'aragaoconstrutora',
    storageBucket: 'aragaoconstrutora.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJDV2_WsuFeV5p_h6RUfHBMg-zZOG_tsw',
    appId: '1:285694691893:ios:dcd31c001c6ec6af91ff7c',
    messagingSenderId: '285694691893',
    projectId: 'aragaoconstrutora',
    storageBucket: 'aragaoconstrutora.appspot.com',
    iosBundleId: 'br.app.aragao.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJDV2_WsuFeV5p_h6RUfHBMg-zZOG_tsw',
    appId: '1:285694691893:ios:dcd31c001c6ec6af91ff7c',
    messagingSenderId: '285694691893',
    projectId: 'aragaoconstrutora',
    storageBucket: 'aragaoconstrutora.appspot.com',
    iosBundleId: 'br.app.aragao.app',
  );
}
